name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Create config.js from secrets
      run: |
        cat > config.js << 'EOF'
        // 自动生成的配置文件（来自GitHub Secrets）
        if (typeof window !== 'undefined') {
          window.firebaseConfig = {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            databaseURL: "${{ secrets.FIREBASE_DATABASE_URL }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}"
          };
          
          window.externalFormConfig = {
            apiBaseUrl: '${{ secrets.EXTERNAL_FORM_API_URL }}',
            auth: {
              username: '${{ secrets.EXTERNAL_FORM_USERNAME }}',
              password: '${{ secrets.EXTERNAL_FORM_PASSWORD }}',
              token: null
            }
          };
        }
        EOF
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
